### PR TITLE
Update spec-mocha for purescript 0.12

### PR DESCRIPTION
**Pull request by AlexaDeWit**

### CODE REVIEW

**Comment by AlexaDeWit** [comment]
Sorry about that, forgot to update the travis config

**Comment by AlexaDeWit** [comment]
This PR also resolves the travisCI issues. Sorry for the two-in one instead of two PRs, but I don't like to submit PRs that don't build ;)

**Comment by owickstrom** [comment]
Thanks for the PR! 😃

**Comment by AlexaDeWit** [comment]
No problem. Mind @ing me when you do the release bump?

**Comment by owickstrom** [comment]
OK, v3.0.0 is published now.

**Comment by AlexaDeWit** [comment]
<3

**Pull request merged**
